# **what?**
# Mirrors issues into Jira. Includes the information: title
# description, GitHub Issue ID and URL

# **why?**
# Jira is our tool for tracking and we need to see these issues in there

# **when?**
# On issue creation or when an issue is labeled `Jira`

name: Jira Issue Creation

on:
  issues:
    types: [opened, labeled]
    
permissions:
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: |
      ((github.event.action == 'opened') || 
      (github.event.action == 'labeled' && github.event.label.name == 'jira'))
    steps:
      - name: Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create JIRA Ticket
        id: create
        uses: atlassian/gajira-create@v2.0.1
        with:
          project: CORE
          issuetype: Task
          summary: '${{ github.event.issue.title }}'
          description: |
            ${{ github.event.issue.body }} \n\n_GitHub URL:_ ${{ github.event.issue.html_url }} \n_Author:_ ${{ github.event.issue.user.login }}
          fields: '{ "labels": ["triage"], "customfield_10045": "${{ github.event.issue.html_url }}", "customfield_10046": ${{ github.event.issue.number }} }'

      - name: Update GitHub Issue
        uses: ./jira/gajira-issue-update
        with:
          issue_number: "{{ event.issue.id }}"
          owner: "{{ event.repository.owner.login }}"
          name: "{{ event.repository.name }}"
          jira: "${{ steps.create.outputs.issue }}"
